// Name: LIM RUI YANG RYAN
// Admin No: 252206Z
// Tutorial Group: IT2508
// <auto-generated />
using System;
using ArcaneVault.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801114828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ArcaneVault.Api.Models.ArcaneVaultUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("ArcaneVaultUsers", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.ArcaneVaultUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("ArcaneVaultUserRoles", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryCode");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.CollectionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.CollectionItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.ArcaneVaultUser", b =>
                {
                    b.HasOne("ArcaneVault.Api.Models.ArcaneVaultUserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.CollectionItem", b =>
                {
                    b.HasOne("ArcaneVault.Api.Models.ArcaneVaultUser", "User")
                        .WithMany("CollectionItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.CollectionItemCategory", b =>
                {
                    b.HasOne("ArcaneVault.Api.Models.Category", "Category")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Api.Models.CollectionItem", "CollectionItem")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.ArcaneVaultUser", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.ArcaneVaultUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.Category", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.Api.Models.CollectionItem", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
